services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  static-site:
    build: ./requirements/bonus/static-site
    container_name: static-site
    restart: no
    volumes:
      - static_site_data:/var/www/static-site
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped        
    ports: 
      - "443:443"
    secrets:
      - ad_password
    env_file:
      - .env                   
    volumes:                          
      - /home/izahr/data/nginx/ssl:/etc/nginx/ssl
      - /home/izahr/data/nginx/conf:/etc/nginx/conf.d:ro
      - wordpress_data:/var/www/html
      - static_site_data:/var/www/static:ro
    networks:                         
      - inception
    depends_on:
      - wordpress
      - mariadb
      - adminer

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:                      
      - .env
    secrets:
      - db_password
      - credentials
    volumes:                                  
      - wordpress_data:/var/www/html         
    networks:                                 
      - inception
    depends_on:
      - mariadb
      - redis

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - adminer_data:/var/www/adminer

  redis:
    build: ./requirements/bonus/redis-cache
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - redis_cache_data:/data

  ftp-server:
    build: ./requirements/bonus/ftp-server
    container_name: ftp-server
    restart: unless-stopped
    networks:
      - inception
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    secrets:
      - vsftp_password

  cadvisor:
    build: ./requirements/bonus/cAdvisor
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8888:8888"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - cAdvisor_data:/var/log/cadvisor
    networks:
      - inception
    devices:
      - /dev/kmsg

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/izahr/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/izahr/data/wordpress
      o: bind

  static_site_data:
    driver: local
    driver_opts:
      type: none
      device: /home/izahr/data/static-site
      o: bind

  adminer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/izahr/data/adminer
      o: bind

  redis_cache_data:
    driver: local
    driver_opts:
      type: none
      device: /home/izahr/data/redis-cache
      o: bind

  cAdvisor_data:
    driver: local
    driver_opts:
      type: none
      device: /home/izahr/data/cAdvisor
      o: bind

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  credentials:
    file: ../secrets/credentials.txt
  ad_password:
    file: ../secrets/adminer_password.txt
  vsftp_password:
    file: ../secrets/vsftp_password.txt

